---
title: "Analisis del viento y de la temperatura en Nueva York"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### El viento en Nueva York

```{r viento, echo=FALSE}
hist(airquality$Wind, ylab = "Distribución", xlab = "Viento", main = "Histograma del viento en Nueva York", col= "Blue")
```

### La temperatura en Nueva York

```{r pressure, echo=FALSE}
hist(airquality$Temp, ylab = "Distribución", xlab = "Temperatura", main = "Histograma de la temperatura de Nueva York", col= "blue")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Resumen del viento en Nueva York

```{r wind}
summary(airquality$Wind)
```


### Resumen de la temperatura en Nueva York

```{r temp}
summary(airquality$Temp)
```